<?php

namespace AppBundle\Repository;

/**
 * BrickRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrickRepository extends \Doctrine\ORM\EntityRepository
{
}
